FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
WORKDIR /app

COPY src/MatchMaking.Common/. ./
COPY src/MatchMaking.Worker/. ./
RUN dotnet restore MatchMaking.Common.csproj
RUN dotnet publish MatchMaking.Worker.csproj -c Release -o /app/publish

FROM mcr.microsoft.com/dotnet/aspnet:9.0 AS runtime
WORKDIR /app
COPY --from=build /app/publish ./

ENTRYPOINT ["dotnet", "MatchMaking.Worker.dll"]
